config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:index, :new, :create]
  resources :courses, only: [:index, :show, :new, :create]
  resources :classrooms, only: [:new, :create]
  root 'welcome#index'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :course
  belongs_to :student
  validates :course_id, presence: { message: 'Curso não pode estar em branco' }
  validates :student_id, presence: { message: 'Aluno não pode estar em branco' }
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  validates :name, presence: { message: 'Nome não pode estar em branco' }
  validates :description, presence: { message: 'Descrição não pode estar em branco' }
  validates :status, presence: { message: 'Status não pode estar em branco' }
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  validates :name, presence: { message: 'Nome não pode estar em branco' }
  validates :register_number, numericality: { message: 'Numero de registro inválido' }
  validates :status, presence: { message: 'Status não pode estar em branco' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      redirect_to course_path(@classroom.course)
      flash[:notice] = 'Matricula realizada com sucesso'
    else
      render :new
    end
  end

  private

  def classroom_params
    params.require(:classroom).permit(:student_id, :course_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :status)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to action: :index
      flash[:notice] = 'Aluno criado com sucesso'
    else
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/new.html.erb
<div class="page-header">
  <h1>Nova matricula</h1>
</div>
<%= simple_form_for @classroom do |f| %>
  <%= f.association :student, label: 'Aluno' %>
  <%= f.association :course, label: 'Curso' %>
  <%= f.button :submit, 'Cadastrar Matricula' %>
<% end %>

app/views/courses/_course.html.erb
<p><strong>Nome: </strong><%= link_to course.name, course %></p>
<p><strong>Descrição: </strong><%= course.description %></p>
<p><strong>Status: </strong><%= course.status %></p>

app/views/courses/index.html.erb
<div class="row">
  <% if flash[:notice] %>
    <div class="notice bg-success"><%= flash[:notice] %></div>
  <% end %>
  <div class="page-header">
    <h1>Lista de cursos</h1>
  </div>
  <br>
  <% @courses.each do |course| %>
    <div class="course col-md-6">
      <%= render partial: 'course', locals: { course: course } %>
    </div>
  <% end %>
  <br>
</div>

app/views/courses/new.html.erb
<div class="page-header">
  <h1>Novo curso</h1>
</div>
<br>
<%= simple_form_for @course do |f| %>
  <%= f.input :name, label: 'Nome' %>
  <%= f.input :description, label: 'Descrição' %>
  <%= f.input :status %>
  <%= f.button :submit, 'Cadastrar Curso' %>
<% end %>

app/views/courses/show.html.erb
<div class="row">
  <% if flash[:notice] %>
    <div class="notice bg-success"><%= flash[:notice] %></div>
  <% end %>
  <div class="page-header">
    <h1>Informações sobre o curso</h1>
  </div>
  <div class="course">
    <%= render partial: 'course', locals: { course: @course } %>
  </div>
  <br>
  <h2>Matriculas</h2>
  <% @course.classrooms.each do |classroom| %>
    <div class="classroom col-md-6">
      <p><strong>Nome: </strong><%= classroom.student.name %></p>
      <p><strong>Data de ingresso: </strong><%= classroom.created_at %></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <%= render 'shared/navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-menu" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'ProficiencyTest', root_path, class: 'navbar-brand' %>
  </div>
    <div class="collapse navbar-collapse" id="collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Cadastrar novo aluno', new_student_path %></li>
        <li><%= link_to 'Lista de alunos', students_path %></li>
        <li><%= link_to 'Cadastrar novo curso', new_course_path %></li>
        <li><%= link_to 'Lista de cursos', courses_path %></li>
        <li><%= link_to 'Nova matricula', new_classroom_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/students/index.html.erb
<div class="row">
  <% if flash[:notice] %>
    <div class="notice bg-success"><%= flash[:notice] %></div>
  <% end %>
  <div class="page-header">
    <h1>Lista de alunos</h1>
  </div>
  <br>
  <% @students.each do |student| %>
    <div class="student col-md-6">
      <p><strong>Name: </strong><%= student.name %></p>
      <p><strong>Numero de registro: </strong><%= student.register_number %></p>
      <p><strong>Status: </strong><%= student.status %></p>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<div class="page-header">
  <h1>Novo aluno</h1>
</div>
<br>
<%= simple_form_for @student do |f| %>
  <%= f.input :name, label: 'Nome' , input_html: { required: 'required'} %>
  <%= f.input :register_number, label: 'Numero de registro' %>
  <%= f.input :status %>
  <%= f.button :submit, 'Cadastrar Aluno' %>
<% end %>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1 class="text-center">Bem-vindo</h1>
</div>